version: '3.8'

services:
  bluetooth-manager:

    image: ghcr.io/wswv/bluezweb-docker
    container_name: bluetooth-manager
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
    restart: unless-stopped

  # Loki service for centralized logging (optional)
  # Uncomment to enable Loki logging
  # loki:
  #   image: grafana/loki:2.9.2
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - loki-data:/loki
  #   restart: unless-stopped

# volumes:
#   loki-data: