version: '3.8'

services:
  bluetooth-manager:

    image: ghcr.io/wswv/bluezweb-docker
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  # Loki service for centralized logging (optional)
  # Uncomment to enable Loki logging
  # loki:
  #   image: grafana/loki:2.9.2
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - loki-data:/loki
  #   restart: unless-stopped

# volumes:
#   loki-data: